// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/cmm" | "/analytics" | "/capture" | "/capture/work/[componentId]" | "/dashboard" | "/demo" | "/forms" | "/glasses-demo" | "/inspect" | "/integrity" | "/login" | "/parts/[id]" | "/print-labels" | "/sessions" | "/sessions/[id]" | "/shifts" | "/shifts/[id]" | "/technicians"
type AppRouteHandlerRoutes = "/api/admin/debug" | "/api/admin/upload-cmm" | "/api/ai/extract-document" | "/api/ai/generate-8130" | "/api/ai/generate-workorder" | "/api/ai/structure-voice" | "/api/alerts" | "/api/auth/[...nextauth]" | "/api/auth/check" | "/api/auth/verify-passcode" | "/api/capture-documents/download/[id]" | "/api/capture/sessions" | "/api/cmm/lookup" | "/api/components" | "/api/components/[id]" | "/api/components/[id]/compliance" | "/api/documents/[id]/provenance" | "/api/documents/download/[id]" | "/api/documents/render-8130-pdf" | "/api/documents/sign" | "/api/exceptions" | "/api/exceptions/[id]" | "/api/exceptions/scan-all" | "/api/exceptions/scan/[componentId]" | "/api/export/trace/[componentId]" | "/api/measurement-specs" | "/api/measurement-specs/[id]" | "/api/measurements/[id]" | "/api/mobile/analyze-image" | "/api/mobile/analyze-session" | "/api/mobile/annotate-video" | "/api/mobile/auth" | "/api/mobile/create-document" | "/api/mobile/evidence" | "/api/mobile/evidence/upload" | "/api/mobile/evidence/upload-callback" | "/api/mobile/generate" | "/api/mobile/sessions" | "/api/mobile/sessions/[id]" | "/api/mobile/transcribe" | "/api/mobile/verify-documents" | "/api/mobile/work" | "/api/realtime-transcription/save" | "/api/realtime-transcription/session" | "/api/sessions" | "/api/sessions/[id]" | "/api/sessions/[id]/audit" | "/api/sessions/[id]/create-document" | "/api/sessions/[id]/documents/[docId]" | "/api/sessions/[id]/review" | "/api/shifts" | "/api/shifts/[id]" | "/api/shifts/[id]/audio" | "/api/shifts/[id]/export" | "/api/shifts/[id]/measurements" | "/api/shifts/[id]/reconcile" | "/api/shifts/[id]/transcript" | "/api/shifts/[id]/video" | "/api/technicians" | "/api/technicians/verify-certificate"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/cmm": {}
  "/analytics": {}
  "/api/admin/debug": {}
  "/api/admin/upload-cmm": {}
  "/api/ai/extract-document": {}
  "/api/ai/generate-8130": {}
  "/api/ai/generate-workorder": {}
  "/api/ai/structure-voice": {}
  "/api/alerts": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/check": {}
  "/api/auth/verify-passcode": {}
  "/api/capture-documents/download/[id]": { "id": string; }
  "/api/capture/sessions": {}
  "/api/cmm/lookup": {}
  "/api/components": {}
  "/api/components/[id]": { "id": string; }
  "/api/components/[id]/compliance": { "id": string; }
  "/api/documents/[id]/provenance": { "id": string; }
  "/api/documents/download/[id]": { "id": string; }
  "/api/documents/render-8130-pdf": {}
  "/api/documents/sign": {}
  "/api/exceptions": {}
  "/api/exceptions/[id]": { "id": string; }
  "/api/exceptions/scan-all": {}
  "/api/exceptions/scan/[componentId]": { "componentId": string; }
  "/api/export/trace/[componentId]": { "componentId": string; }
  "/api/measurement-specs": {}
  "/api/measurement-specs/[id]": { "id": string; }
  "/api/measurements/[id]": { "id": string; }
  "/api/mobile/analyze-image": {}
  "/api/mobile/analyze-session": {}
  "/api/mobile/annotate-video": {}
  "/api/mobile/auth": {}
  "/api/mobile/create-document": {}
  "/api/mobile/evidence": {}
  "/api/mobile/evidence/upload": {}
  "/api/mobile/evidence/upload-callback": {}
  "/api/mobile/generate": {}
  "/api/mobile/sessions": {}
  "/api/mobile/sessions/[id]": { "id": string; }
  "/api/mobile/transcribe": {}
  "/api/mobile/verify-documents": {}
  "/api/mobile/work": {}
  "/api/realtime-transcription/save": {}
  "/api/realtime-transcription/session": {}
  "/api/sessions": {}
  "/api/sessions/[id]": { "id": string; }
  "/api/sessions/[id]/audit": { "id": string; }
  "/api/sessions/[id]/create-document": { "id": string; }
  "/api/sessions/[id]/documents/[docId]": { "id": string; "docId": string; }
  "/api/sessions/[id]/review": { "id": string; }
  "/api/shifts": {}
  "/api/shifts/[id]": { "id": string; }
  "/api/shifts/[id]/audio": { "id": string; }
  "/api/shifts/[id]/export": { "id": string; }
  "/api/shifts/[id]/measurements": { "id": string; }
  "/api/shifts/[id]/reconcile": { "id": string; }
  "/api/shifts/[id]/transcript": { "id": string; }
  "/api/shifts/[id]/video": { "id": string; }
  "/api/technicians": {}
  "/api/technicians/verify-certificate": {}
  "/capture": {}
  "/capture/work/[componentId]": { "componentId": string; }
  "/dashboard": {}
  "/demo": {}
  "/forms": {}
  "/glasses-demo": {}
  "/inspect": {}
  "/integrity": {}
  "/login": {}
  "/parts/[id]": { "id": string; }
  "/print-labels": {}
  "/sessions": {}
  "/sessions/[id]": { "id": string; }
  "/shifts": {}
  "/shifts/[id]": { "id": string; }
  "/technicians": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
