// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(dashboard)/admin/cmm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cmm">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/admin/cmm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/capture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/capture">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/capture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/capture/work/[componentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/capture/work/[componentId]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/capture/work/[componentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/forms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/forms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/inspect/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inspect">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/inspect/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/integrity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrity">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/integrity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/parts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parts/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/parts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sessions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sessions/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sessions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sessions">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/shifts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shifts/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/shifts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/shifts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shifts">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/shifts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/technicians/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/technicians">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/technicians/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/glasses-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/glasses-demo">> = Specific
  const handler = {} as typeof import("../../app/glasses-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/print-labels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/print-labels">> = Specific
  const handler = {} as typeof import("../../app/print-labels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/debug">> = Specific
  const handler = {} as typeof import("../../app/api/admin/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/upload-cmm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/upload-cmm">> = Specific
  const handler = {} as typeof import("../../app/api/admin/upload-cmm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/extract-document/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/extract-document">> = Specific
  const handler = {} as typeof import("../../app/api/ai/extract-document/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/generate-8130/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/generate-8130">> = Specific
  const handler = {} as typeof import("../../app/api/ai/generate-8130/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/generate-workorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/generate-workorder">> = Specific
  const handler = {} as typeof import("../../app/api/ai/generate-workorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/structure-voice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/structure-voice">> = Specific
  const handler = {} as typeof import("../../app/api/ai/structure-voice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alerts">> = Specific
  const handler = {} as typeof import("../../app/api/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/check">> = Specific
  const handler = {} as typeof import("../../app/api/auth/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/verify-passcode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-passcode">> = Specific
  const handler = {} as typeof import("../../app/api/auth/verify-passcode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/capture-documents/download/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/capture-documents/download/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/capture-documents/download/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/capture/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/capture/sessions">> = Specific
  const handler = {} as typeof import("../../app/api/capture/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cmm/lookup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cmm/lookup">> = Specific
  const handler = {} as typeof import("../../app/api/cmm/lookup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/components/[id]/compliance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/components/[id]/compliance">> = Specific
  const handler = {} as typeof import("../../app/api/components/[id]/compliance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/components/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/components/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/components/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/components/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/components">> = Specific
  const handler = {} as typeof import("../../app/api/components/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/documents/[id]/provenance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]/provenance">> = Specific
  const handler = {} as typeof import("../../app/api/documents/[id]/provenance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/documents/download/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/download/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/documents/download/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/documents/render-8130-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/render-8130-pdf">> = Specific
  const handler = {} as typeof import("../../app/api/documents/render-8130-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/documents/sign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/sign">> = Specific
  const handler = {} as typeof import("../../app/api/documents/sign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/exceptions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exceptions/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/exceptions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/exceptions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exceptions">> = Specific
  const handler = {} as typeof import("../../app/api/exceptions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/exceptions/scan-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exceptions/scan-all">> = Specific
  const handler = {} as typeof import("../../app/api/exceptions/scan-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/exceptions/scan/[componentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exceptions/scan/[componentId]">> = Specific
  const handler = {} as typeof import("../../app/api/exceptions/scan/[componentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/export/trace/[componentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/trace/[componentId]">> = Specific
  const handler = {} as typeof import("../../app/api/export/trace/[componentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/measurement-specs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/measurement-specs/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/measurement-specs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/measurement-specs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/measurement-specs">> = Specific
  const handler = {} as typeof import("../../app/api/measurement-specs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/measurements/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/measurements/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/measurements/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/analyze-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/analyze-image">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/analyze-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/analyze-session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/analyze-session">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/analyze-session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/annotate-video/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/annotate-video">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/annotate-video/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/auth">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/create-document/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/create-document">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/create-document/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/evidence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/evidence">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/evidence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/evidence/upload-callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/evidence/upload-callback">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/evidence/upload-callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/evidence/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/evidence/upload">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/evidence/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/generate">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/sessions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/sessions/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/sessions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/sessions">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/transcribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/transcribe">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/transcribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/verify-documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/verify-documents">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/verify-documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/work/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/work">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/work/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/realtime-transcription/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/realtime-transcription/save">> = Specific
  const handler = {} as typeof import("../../app/api/realtime-transcription/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/realtime-transcription/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/realtime-transcription/session">> = Specific
  const handler = {} as typeof import("../../app/api/realtime-transcription/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[id]/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[id]/audit">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[id]/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[id]/create-document/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[id]/create-document">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[id]/create-document/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[id]/documents/[docId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[id]/documents/[docId]">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[id]/documents/[docId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[id]/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[id]/review">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[id]/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shifts/[id]/audio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shifts/[id]/audio">> = Specific
  const handler = {} as typeof import("../../app/api/shifts/[id]/audio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shifts/[id]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shifts/[id]/export">> = Specific
  const handler = {} as typeof import("../../app/api/shifts/[id]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shifts/[id]/measurements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shifts/[id]/measurements">> = Specific
  const handler = {} as typeof import("../../app/api/shifts/[id]/measurements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shifts/[id]/reconcile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shifts/[id]/reconcile">> = Specific
  const handler = {} as typeof import("../../app/api/shifts/[id]/reconcile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shifts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shifts/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/shifts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shifts/[id]/transcript/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shifts/[id]/transcript">> = Specific
  const handler = {} as typeof import("../../app/api/shifts/[id]/transcript/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shifts/[id]/video/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shifts/[id]/video">> = Specific
  const handler = {} as typeof import("../../app/api/shifts/[id]/video/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shifts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shifts">> = Specific
  const handler = {} as typeof import("../../app/api/shifts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/technicians/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/technicians">> = Specific
  const handler = {} as typeof import("../../app/api/technicians/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/technicians/verify-certificate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/technicians/verify-certificate">> = Specific
  const handler = {} as typeof import("../../app/api/technicians/verify-certificate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
