// Shared PDF renderer functions for FAA compliance documents
// Used by the download route and unit tests
// Renders 8130-3, 337, and 8010-4 forms using pdf-lib

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { parseSpecRange, parseActualValue, checkPassFail } from "./measurement-validation";

// ── Shared types for pdf-lib page drawing ──
type PDFPage = ReturnType<
  Awaited<ReturnType<typeof PDFDocument.create>>["addPage"]
>;
type PDFFont = Awaited<
  ReturnType<Awaited<ReturnType<typeof PDFDocument.create>>["embedFont"]>
>;

// ── Constants ──
const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN = 40;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const BLACK = rgb(0, 0, 0);
const GRAY = rgb(0.4, 0.4, 0.4);
const LIGHT_GRAY = rgb(0.85, 0.85, 0.85);
const DARK_BLUE = rgb(0.1, 0.15, 0.35);

// ── Shared helper: wrap text to fit within a max width ──
// Returns the Y position after drawing all lines.
function drawWrappedText(
  page: PDFPage,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  textFont: PDFFont,
  fontSize: number,
  color = BLACK
): number {
  const words = text.split(/\s+/);
  let line = "";
  let currentY = y;

  for (const word of words) {
    const testLine = line ? `${line} ${word}` : word;
    const testWidth = textFont.widthOfTextAtSize(testLine, fontSize);
    if (testWidth > maxWidth && line) {
      page.drawText(line, {
        x,
        y: currentY,
        size: fontSize,
        font: textFont,
        color,
      });
      currentY -= fontSize + 3;
      line = word;
    } else {
      line = testLine;
    }
  }
  if (line) {
    page.drawText(line, {
      x,
      y: currentY,
      size: fontSize,
      font: textFont,
      color,
    });
    currentY -= fontSize + 3;
  }
  return currentY;
}

// ── Shared helper: draw a horizontal rule ──
function drawLine(page: PDFPage, y: number) {
  page.drawLine({
    start: { x: MARGIN, y },
    end: { x: PAGE_WIDTH - MARGIN, y },
    thickness: 0.5,
    color: GRAY,
  });
}

// ── Shared helper: draw a small gray field label ──
function drawLabel(
  page: PDFPage,
  text: string,
  x: number,
  y: number,
  font: PDFFont
) {
  page.drawText(text, { x, y, size: 6.5, font, color: GRAY });
}

// ── Shared helper: draw a section header bar ──
function drawSectionHeader(
  page: PDFPage,
  text: string,
  y: number,
  fontBold: PDFFont
): number {
  page.drawRectangle({
    x: MARGIN,
    y: y - 14,
    width: CONTENT_WIDTH,
    height: 18,
    color: LIGHT_GRAY,
  });
  page.drawText(text, {
    x: MARGIN + 8,
    y: y - 10,
    size: 8,
    font: fontBold,
    color: DARK_BLUE,
  });
  return y - 22;
}

// ── Shared helper: draw a labeled field (label + value) ──
function drawField(
  page: PDFPage,
  label: string,
  value: string,
  x: number,
  y: number,
  font: PDFFont,
  fontBold: PDFFont,
  bold = false
): number {
  page.drawText(label, { x, y, size: 6.5, font, color: GRAY });
  page.drawText(value || "—", {
    x,
    y: y - 11,
    size: bold ? 10 : 9,
    font: bold ? fontBold : font,
    color: BLACK,
  });
  return y - 26;
}

// ── Shared helper: AeroVision footer ──
function drawFooter(page: PDFPage, font: PDFFont, hash?: string | null) {
  const y = 35;
  page.drawRectangle({
    x: MARGIN,
    y: y - 5,
    width: CONTENT_WIDTH,
    height: 18,
    color: LIGHT_GRAY,
  });
  page.drawText(
    "AeroVision Digital Verification  |  Tamper-evident  |  Generated by AeroVision AI v1.0",
    { x: MARGIN + 10, y: y, size: 6.5, font, color: GRAY }
  );
  if (hash) {
    page.drawText(`SHA-256: ${hash}`, {
      x: PAGE_WIDTH - MARGIN - 120,
      y: y,
      size: 6,
      font,
      color: GRAY,
    });
  }
}

// ══════════════════════════════════════════════════════════════
// PDF RENDERER: FAA Form 8130-3
// ══════════════════════════════════════════════════════════════
export async function render8130Pdf(
  content: Record<string, string>,
  hash?: string | null
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const fontMono = await pdf.embedFont(StandardFonts.Courier);

  let page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - 40;
  const midX = MARGIN + CONTENT_WIDTH / 2;

  // Form header
  page.drawRectangle({
    x: MARGIN,
    y: y - 30,
    width: CONTENT_WIDTH,
    height: 35,
    color: LIGHT_GRAY,
  });
  page.drawText("AUTHORIZED RELEASE CERTIFICATE", {
    x: MARGIN + 10,
    y: y - 18,
    size: 14,
    font: fontBold,
    color: DARK_BLUE,
  });
  page.drawText("FAA Form 8130-3", {
    x: MARGIN + 10,
    y: y - 28,
    size: 7,
    font,
    color: GRAY,
  });
  page.drawText("OMB No. 2120-0020", {
    x: PAGE_WIDTH - MARGIN - 100,
    y: y - 18,
    size: 7,
    font,
    color: GRAY,
  });
  y -= 45;
  drawLine(page, y);

  // Block 1 & 2
  y -= 5;
  drawLabel(
    page,
    "1. Approving Civil Aviation Authority / Country",
    MARGIN + 5,
    y,
    font
  );
  y -= 12;
  page.drawText(content.block1 || "FAA", {
    x: MARGIN + 5,
    y,
    size: 10,
    font: fontBold,
    color: BLACK,
  });
  drawLabel(page, "2. Authorized Release Document", midX + 10, y + 12, font);
  page.drawText(content.block2 || "Authorized Release Certificate", {
    x: midX + 10,
    y,
    size: 9,
    font,
    color: BLACK,
  });
  page.drawLine({
    start: { x: midX, y: y + 18 },
    end: { x: midX, y: y - 16 },
    thickness: 0.5,
    color: GRAY,
  });
  y -= 25;
  drawLine(page, y);

  // Block 3 & 4
  y -= 5;
  drawLabel(page, "3. Form Tracking Number", MARGIN + 5, y, font);
  y -= 12;
  page.drawText(content.block3 || "—", {
    x: MARGIN + 5,
    y,
    size: 10,
    font: fontMono,
    color: DARK_BLUE,
  });
  drawLabel(page, "4. Organization Name and Address", midX + 10, y + 12, font);
  const block4Lines = (content.block4 || "—").split("\n");
  let block4Y = y;
  for (const line of block4Lines) {
    page.drawText(line.trim(), {
      x: midX + 10,
      y: block4Y,
      size: 8,
      font,
      color: BLACK,
    });
    block4Y -= 11;
  }
  page.drawLine({
    start: { x: midX, y: y + 18 },
    end: { x: midX, y: Math.min(block4Y + 5, y - 10) },
    thickness: 0.5,
    color: GRAY,
  });
  y = Math.min(block4Y + 5, y - 15) - 10;
  drawLine(page, y);

  // Block 5
  y -= 5;
  drawLabel(
    page,
    "5. Work Order / Contract / Invoice Number",
    MARGIN + 5,
    y,
    font
  );
  y -= 12;
  page.drawText(content.block5 || "—", {
    x: MARGIN + 5,
    y,
    size: 9,
    font: fontMono,
    color: BLACK,
  });
  y -= 15;
  drawLine(page, y);

  // Block 6 — Item details
  y -= 5;
  const col6Width = CONTENT_WIDTH / 5;
  drawLabel(page, "6a. Item Description", MARGIN + 5, y, font);
  y -= 12;
  page.drawText(content.block6a || "—", {
    x: MARGIN + 5,
    y,
    size: 9,
    font: fontBold,
    color: BLACK,
  });
  const row6Y = y - 20;
  drawLabel(page, "6b. Part Number", MARGIN + 5, row6Y + 8, font);
  page.drawText(content.block6b || "—", {
    x: MARGIN + 5,
    y: row6Y - 4,
    size: 10,
    font: fontMono,
    color: BLACK,
  });
  drawLabel(
    page,
    "6c. Serial Number",
    MARGIN + col6Width * 2,
    row6Y + 8,
    font
  );
  page.drawText(content.block6c || "—", {
    x: MARGIN + col6Width * 2,
    y: row6Y - 4,
    size: 10,
    font: fontMono,
    color: BLACK,
  });
  drawLabel(page, "6d. Qty", MARGIN + col6Width * 4, row6Y + 8, font);
  page.drawText(content.block6d || "1", {
    x: MARGIN + col6Width * 4,
    y: row6Y - 4,
    size: 10,
    font: fontMono,
    color: BLACK,
  });
  y = row6Y - 20;

  // 6e — Status
  drawLabel(page, "6e. Status / Work", MARGIN + 5, y, font);
  y -= 12;
  const statuses = [
    "Overhauled",
    "Repaired",
    "Inspected",
    "Modified",
    "Tested",
    "New",
  ];
  let statusX = MARGIN + 5;
  for (const status of statuses) {
    const checked =
      (content.block6e || "").toLowerCase() === status.toLowerCase();
    page.drawRectangle({
      x: statusX,
      y: y - 2,
      width: 8,
      height: 8,
      borderColor: BLACK,
      borderWidth: 0.5,
      color: checked ? rgb(0.15, 0.15, 0.15) : rgb(1, 1, 1),
    });
    if (checked)
      page.drawText("X", {
        x: statusX + 1.5,
        y: y - 0.5,
        size: 7,
        font: fontBold,
        color: rgb(1, 1, 1),
      });
    page.drawText(status, {
      x: statusX + 11,
      y,
      size: 7.5,
      font,
      color: BLACK,
    });
    statusX += font.widthOfTextAtSize(status, 7.5) + 22;
  }
  y -= 18;
  drawLine(page, y);

  // Block 7 — Remarks (long content, handles page overflow)
  y -= 5;
  drawLabel(page, "7. Description — Status / Work", MARGIN + 5, y, font);
  y -= 14;
  const block7Lines = (content.block7 || "—").split("\n");
  for (const rawLine of block7Lines) {
    const trimmed = rawLine.trim();
    if (!trimmed) {
      y -= 6;
      continue;
    }
    const isHeading =
      trimmed === trimmed.toUpperCase() &&
      trimmed.length < 50 &&
      trimmed.length > 3;
    if (y < 80) {
      page.drawText(`Page ${pdf.getPageCount()}`, {
        x: PAGE_WIDTH - MARGIN - 40,
        y: 25,
        size: 7,
        font,
        color: GRAY,
      });
      page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      y = PAGE_HEIGHT - 50;
      drawLabel(
        page,
        "7. Description — Status / Work (continued)",
        MARGIN + 5,
        y,
        font
      );
      y -= 14;
    }
    y = drawWrappedText(
      page,
      trimmed,
      MARGIN + 10,
      y,
      CONTENT_WIDTH - 20,
      isHeading ? fontBold : font,
      isHeading ? 8.5 : 8
    );
    y -= 2;
  }
  y -= 5;
  drawLine(page, y);

  // Blocks 8-14 (if space, otherwise new page)
  if (y < 200) {
    page.drawText(`Page ${pdf.getPageCount()}`, {
      x: PAGE_WIDTH - MARGIN - 40,
      y: 25,
      size: 7,
      font,
      color: GRAY,
    });
    page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    y = PAGE_HEIGHT - 50;
  }

  // Blocks 8-10
  y -= 5;
  drawLabel(page, "8–10. Eligibility / Conformity", MARGIN + 5, y, font);
  y -= 12;
  page.drawText(
    "[X] Condition for safe operation    [X] FAR § 43.9, 14 CFR Part 145",
    { x: MARGIN + 10, y, size: 7.5, font, color: BLACK }
  );
  y -= 15;
  drawLine(page, y);

  // Blocks 11 & 12
  y -= 5;
  drawLabel(
    page,
    "11. Approval / Authorization Number",
    MARGIN + 5,
    y,
    font
  );
  drawLabel(page, "12. Date", midX + 10, y, font);
  y -= 12;
  page.drawText(content.block11 || "—", {
    x: MARGIN + 5,
    y,
    size: 9,
    font: fontMono,
    color: BLACK,
  });
  page.drawText(content.block12 || "—", {
    x: midX + 10,
    y,
    size: 9,
    font: fontMono,
    color: BLACK,
  });
  y -= 20;
  drawLine(page, y);

  // Block 13 — Signature
  y -= 5;
  drawLabel(page, "13. Authorized Signature", MARGIN + 5, y, font);
  y -= 15;
  page.drawRectangle({
    x: MARGIN + 10,
    y: y - 25,
    width: 180,
    height: 30,
    borderColor: GRAY,
    borderWidth: 0.5,
  });
  page.drawText(content.block13 || "[PENDING E-SIGNATURE]", {
    x: MARGIN + 20,
    y: y - 15,
    size: 8,
    font,
    color: GRAY,
  });
  page.drawText(`Date: ${content.block12 || "—"}`, {
    x: MARGIN + 210,
    y: y - 5,
    size: 8,
    font,
    color: BLACK,
  });
  page.drawText(`Auth: ${content.block11 || "—"}`, {
    x: MARGIN + 210,
    y: y - 18,
    size: 8,
    font,
    color: BLACK,
  });
  y -= 40;
  drawLine(page, y);

  // Block 14
  y -= 5;
  drawLabel(page, "14. Certifying Statement", MARGIN + 5, y, font);
  y -= 12;
  drawWrappedText(
    page,
    content.block14 || "—",
    MARGIN + 5,
    y,
    CONTENT_WIDTH - 10,
    font,
    7.5
  );

  // Footer
  drawFooter(page, font, hash);
  page.drawText(`Page ${pdf.getPageCount()}`, {
    x: PAGE_WIDTH - MARGIN - 40,
    y: 25,
    size: 7,
    font,
    color: GRAY,
  });

  return pdf.save();
}

// ══════════════════════════════════════════════════════════════
// PDF RENDERER: FAA Form 337 — Major Repair and Alteration
// ══════════════════════════════════════════════════════════════
export async function render337Pdf(
  content: Record<string, unknown>,
  hash?: string | null
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const fontMono = await pdf.embedFont(StandardFonts.Courier);

  const page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - 40;

  // Header
  page.drawRectangle({
    x: MARGIN,
    y: y - 30,
    width: CONTENT_WIDTH,
    height: 35,
    color: LIGHT_GRAY,
  });
  page.drawText("MAJOR REPAIR AND ALTERATION", {
    x: MARGIN + 10,
    y: y - 18,
    size: 14,
    font: fontBold,
    color: DARK_BLUE,
  });
  page.drawText("FAA Form 337 (10/06)", {
    x: MARGIN + 10,
    y: y - 28,
    size: 7,
    font,
    color: GRAY,
  });
  page.drawText("OMB No. 2120-0020", {
    x: PAGE_WIDTH - MARGIN - 100,
    y: y - 18,
    size: 7,
    font,
    color: GRAY,
  });
  y -= 50;
  drawLine(page, y);

  // Parse sub-objects
  const aircraft = (content.aircraft || {}) as Record<string, string>;
  const owner = (content.owner || {}) as Record<string, string>;
  const appliance = (content.appliance || {}) as Record<string, string>;
  const conformity = (content.conformity || {}) as Record<string, string>;
  const approval = (content.approval || {}) as Record<string, string>;

  // Section 1: Aircraft
  y = drawSectionHeader(page, "1. AIRCRAFT", y, fontBold);
  y -= 5;
  const colW = CONTENT_WIDTH / 4;
  const fields1 = [
    { label: "Nationality & Registration", value: aircraft.registration },
    { label: "Serial No.", value: aircraft.serialNumber },
    { label: "Make", value: aircraft.make },
    { label: "Model / Series", value: aircraft.model },
  ];
  for (let i = 0; i < fields1.length; i++) {
    const x = MARGIN + 5 + colW * i;
    drawLabel(page, fields1[i].label, x, y, font);
    page.drawText(fields1[i].value || "—", {
      x,
      y: y - 11,
      size: 10,
      font: i === 0 ? fontMono : font,
      color: i === 0 ? DARK_BLUE : BLACK,
    });
  }
  y -= 30;
  drawLine(page, y);

  // Section 2: Owner
  y = drawSectionHeader(page, "2. OWNER", y, fontBold);
  y -= 5;
  drawLabel(page, "Name", MARGIN + 5, y, font);
  page.drawText(owner.name || "—", {
    x: MARGIN + 5,
    y: y - 11,
    size: 9,
    font: fontBold,
    color: BLACK,
  });
  const midX = MARGIN + CONTENT_WIDTH / 2;
  drawLabel(page, "Address", midX, y, font);
  const ownerAddr = (owner.address || "—").split("\n");
  let addrY = y - 11;
  for (const line of ownerAddr) {
    page.drawText(line.trim(), {
      x: midX,
      y: addrY,
      size: 8,
      font,
      color: BLACK,
    });
    addrY -= 11;
  }
  y = Math.min(addrY, y - 30) - 5;
  drawLine(page, y);

  // Section 3: Type and Unit Identification
  y = drawSectionHeader(
    page,
    "3. TYPE AND UNIT IDENTIFICATION",
    y,
    fontBold
  );
  y -= 5;
  drawLabel(page, "Type", MARGIN + 5, y, font);
  page.drawText(
    `[X] ${(content.repairType as string) || "Repair"}`,
    { x: MARGIN + 5, y: y - 11, size: 8, font, color: BLACK }
  );
  drawLabel(page, "Unit", MARGIN + 100, y, font);
  page.drawText((content.unit as string) || "APPLIANCE", {
    x: MARGIN + 100,
    y: y - 11,
    size: 8,
    font: fontBold,
    color: BLACK,
  });
  y -= 30;

  // Appliance details
  const appFields = [
    { label: "Make", value: appliance.make },
    { label: "Model / Part No.", value: appliance.model, mono: true },
    { label: "Serial No.", value: appliance.serialNumber, mono: true },
    { label: "Type", value: appliance.type },
  ];
  for (let i = 0; i < appFields.length; i++) {
    const x = MARGIN + 5 + colW * i;
    drawLabel(page, appFields[i].label, x, y, font);
    page.drawText(appFields[i].value || "—", {
      x,
      y: y - 11,
      size: 9,
      font: appFields[i].mono ? fontMono : font,
      color: appFields[i].mono ? DARK_BLUE : BLACK,
    });
  }
  y -= 30;
  drawLine(page, y);

  // Section 4: Conformity Statement
  y = drawSectionHeader(page, "6. CONFORMITY STATEMENT", y, fontBold);
  y -= 5;
  y = drawField(
    page,
    "A. Agency",
    conformity.agency?.split("\n")[0] || "—",
    MARGIN + 5,
    y,
    font,
    fontBold
  );
  y = drawField(
    page,
    "B. Kind of Agency",
    `[X] ${conformity.agencyKind || "Certificated Repair Station"}`,
    MARGIN + 5,
    y,
    font,
    fontBold
  );
  y = drawField(
    page,
    "C. Certificate Number",
    conformity.certificateNumber || "—",
    MARGIN + 5,
    y,
    font,
    fontBold,
    true
  );

  // Certification text
  y -= 5;
  y = drawWrappedText(
    page,
    "D. I certify that the repair made to the unit(s) identified above has been made in accordance with the requirements of Part 43 of the U.S. Federal Aviation Regulations.",
    MARGIN + 5,
    y,
    CONTENT_WIDTH - 10,
    font,
    7.5
  );
  y -= 5;
  page.drawText(conformity.signedBy || "—", {
    x: MARGIN + 10,
    y,
    size: 12,
    font: fontBold,
    color: DARK_BLUE,
  });
  page.drawText(`Date: ${conformity.date || "—"}`, {
    x: MARGIN + 200,
    y,
    size: 8,
    font,
    color: BLACK,
  });
  y -= 20;
  drawLine(page, y);

  // Section 5: Approval for Return to Service
  y = drawSectionHeader(
    page,
    "7. APPROVAL FOR RETURN TO SERVICE",
    y,
    fontBold
  );
  y -= 5;
  page.drawText(
    `[X] ${approval.status || "Approved"}    ${approval.type || "Repair Station"}    Certificate: ${approval.certificate || "—"}`,
    { x: MARGIN + 5, y, size: 8, font, color: BLACK }
  );
  y -= 15;
  page.drawText(approval.signedBy || "—", {
    x: MARGIN + 10,
    y,
    size: 12,
    font: fontBold,
    color: DARK_BLUE,
  });
  page.drawText(`Date: ${approval.date || "—"}`, {
    x: MARGIN + 200,
    y,
    size: 8,
    font,
    color: BLACK,
  });
  y -= 20;
  drawLine(page, y);

  // Section 6: Description of Work
  y = drawSectionHeader(
    page,
    "8. DESCRIPTION OF WORK ACCOMPLISHED",
    y,
    fontBold
  );
  y -= 8;
  const workLines = ((content.workDescription as string) || "—").split("\n");
  for (const rawLine of workLines) {
    const trimmed = rawLine.trim();
    if (!trimmed) {
      y -= 6;
      continue;
    }
    if (y < 70) break; // don't overflow past footer
    y = drawWrappedText(
      page,
      trimmed,
      MARGIN + 5,
      y,
      CONTENT_WIDTH - 10,
      font,
      8
    );
    y -= 2;
  }

  // Footer
  drawFooter(page, font, hash);

  return pdf.save();
}

// ══════════════════════════════════════════════════════════════
// PDF RENDERER: FAA Form 8010-4 — Malfunction or Defect Report
// ══════════════════════════════════════════════════════════════
export async function render8010Pdf(
  content: Record<string, unknown>,
  hash?: string | null
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const fontMono = await pdf.embedFont(StandardFonts.Courier);

  const page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - 40;

  // Header
  page.drawRectangle({
    x: MARGIN,
    y: y - 30,
    width: CONTENT_WIDTH,
    height: 35,
    color: LIGHT_GRAY,
  });
  page.drawText("MALFUNCTION OR DEFECT REPORT", {
    x: MARGIN + 10,
    y: y - 18,
    size: 14,
    font: fontBold,
    color: DARK_BLUE,
  });
  page.drawText("FAA Form 8010-4 (10-92)", {
    x: MARGIN + 10,
    y: y - 28,
    size: 7,
    font,
    color: GRAY,
  });
  page.drawText("OMB No. 2120-0663", {
    x: PAGE_WIDTH - MARGIN - 100,
    y: y - 18,
    size: 7,
    font,
    color: GRAY,
  });
  y -= 50;
  drawLine(page, y);

  // Parse sub-objects
  const aircraft = (content.aircraft || {}) as Record<string, string>;
  const defectPart = (content.defectPart || {}) as Record<string, string>;
  const componentAssembly = (content.componentAssembly || {}) as Record<
    string,
    string
  >;
  const metrics = (content.metrics || {}) as Record<string, string>;
  const submittedBy = (content.submittedBy || {}) as Record<string, string>;
  const colW = CONTENT_WIDTH / 4;

  // Section 1: Aircraft Identification
  y = drawSectionHeader(page, "1. AIRCRAFT IDENTIFICATION", y, fontBold);
  y -= 5;
  const acFields = [
    { label: "Registration No.", value: aircraft.registration, mono: true },
    { label: "Manufacturer", value: aircraft.manufacturer },
    { label: "Model / Series", value: aircraft.model },
    { label: "Serial Number", value: aircraft.serialNumber },
  ];
  for (let i = 0; i < acFields.length; i++) {
    const x = MARGIN + 5 + colW * i;
    drawLabel(page, acFields[i].label, x, y, font);
    page.drawText(acFields[i].value || "—", {
      x,
      y: y - 11,
      size: 10,
      font: acFields[i].mono ? fontMono : font,
      color: acFields[i].mono ? DARK_BLUE : BLACK,
    });
  }
  y -= 30;
  drawLine(page, y);

  // Section 2: Specific Part Causing Trouble
  y = drawSectionHeader(
    page,
    "5. SPECIFIC PART CAUSING TROUBLE",
    y,
    fontBold
  );
  y -= 5;
  const partFields = [
    { label: "Part Name", value: defectPart.name, bold: true },
    {
      label: "MFG Model / Part No.",
      value: defectPart.partNumber,
      mono: true,
    },
    { label: "Serial No.", value: defectPart.serialNumber },
    { label: "Part/Defect Location", value: defectPart.location },
  ];
  for (let i = 0; i < partFields.length; i++) {
    const x = MARGIN + 5 + colW * i;
    drawLabel(page, partFields[i].label, x, y, font);
    const pFont = partFields[i].mono
      ? fontMono
      : partFields[i].bold
        ? fontBold
        : font;
    const pColor = partFields[i].mono
      ? DARK_BLUE
      : partFields[i].bold
        ? rgb(0.6, 0.3, 0)
        : BLACK;
    page.drawText(partFields[i].value || "—", {
      x,
      y: y - 11,
      size: 9,
      font: pFont,
      color: pColor,
    });
  }
  y -= 30;
  drawLine(page, y);

  // Section 3: Component / Appliance
  y = drawSectionHeader(
    page,
    "6. APPLIANCE / COMPONENT (Assembly That Includes Part)",
    y,
    fontBold
  );
  y -= 5;
  const compFields = [
    { label: "Name", value: componentAssembly.name },
    { label: "Manufacturer", value: componentAssembly.manufacturer },
    {
      label: "Model / Part No.",
      value: componentAssembly.partNumber,
      mono: true,
    },
    {
      label: "Serial Number",
      value: componentAssembly.serialNumber,
      mono: true,
    },
  ];
  for (let i = 0; i < compFields.length; i++) {
    const x = MARGIN + 5 + colW * i;
    drawLabel(page, compFields[i].label, x, y, font);
    page.drawText(compFields[i].value || "—", {
      x,
      y: y - 11,
      size: 9,
      font: compFields[i].mono ? fontMono : font,
      color: compFields[i].mono ? DARK_BLUE : BLACK,
    });
  }
  y -= 30;
  drawLine(page, y);

  // Section 4: Metrics
  y = drawSectionHeader(page, "PART METRICS", y, fontBold);
  y -= 5;
  const metricFields = [
    { label: "Part Total Time", value: metrics.partTotalTime },
    { label: "Part TSO", value: metrics.partTSO },
    { label: "Part Condition", value: metrics.partCondition },
    {
      label: "Date Submitted",
      value: (content.dateSubmitted as string) || "—",
    },
  ];
  for (let i = 0; i < metricFields.length; i++) {
    const x = MARGIN + 5 + colW * i;
    drawLabel(page, metricFields[i].label, x, y, font);
    const isCondition = metricFields[i].label === "Part Condition";
    page.drawText(metricFields[i].value || "—", {
      x,
      y: y - 11,
      size: 9,
      font: isCondition ? fontBold : font,
      color: isCondition ? rgb(0.6, 0.3, 0) : BLACK,
    });
  }
  y -= 30;
  drawLine(page, y);

  // Section 5: Comments (long narrative)
  y = drawSectionHeader(page, "8. COMMENTS", y, fontBold);
  y -= 8;
  const commentLines = ((content.comments as string) || "—").split("\n");
  for (const rawLine of commentLines) {
    const trimmed = rawLine.trim();
    if (!trimmed) {
      y -= 6;
      continue;
    }
    const isHeading =
      trimmed === trimmed.toUpperCase() &&
      trimmed.length < 50 &&
      trimmed.length > 3;
    if (y < 100) break;
    y = drawWrappedText(
      page,
      trimmed,
      MARGIN + 5,
      y,
      CONTENT_WIDTH - 10,
      isHeading ? fontBold : font,
      8
    );
    y -= 2;
  }
  y -= 5;
  drawLine(page, y);

  // Section 6: Submitted By
  y -= 10;
  const subFields = [
    { label: "Submitted By", value: submittedBy.type },
    { label: "Operator Designation", value: submittedBy.designation },
    { label: "Telephone", value: submittedBy.telephone },
  ];
  const subColW = CONTENT_WIDTH / 3;
  for (let i = 0; i < subFields.length; i++) {
    const x = MARGIN + 5 + subColW * i;
    drawLabel(page, subFields[i].label, x, y, font);
    page.drawText(subFields[i].value || "—", {
      x,
      y: y - 11,
      size: 9,
      font,
      color: BLACK,
    });
  }

  // Footer
  drawFooter(page, font, hash);

  return pdf.save();
}

// ══════════════════════════════════════════════════════════════
// PDF RENDERER: EASA Form 1 (Authorized Release Certificate)
// ══════════════════════════════════════════════════════════════
// European equivalent of FAA 8130-3. Used by EASA-regulated MROs
// to release parts and appliances back to service after maintenance.
// Blocks 1-14 mirror the official EASA Form 1 layout.

export async function renderEASAForm1Pdf(
  content: Record<string, string>,
  hash?: string | null
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const courier = await pdf.embedFont(StandardFonts.Courier);
  const page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);

  let y = PAGE_HEIGHT - MARGIN;

  // ── Header: EASA Form 1 title block ──
  page.drawRectangle({
    x: MARGIN,
    y: y - 38,
    width: CONTENT_WIDTH,
    height: 42,
    color: rgb(0.05, 0.1, 0.3),
  });
  page.drawText("EASA FORM 1", {
    x: MARGIN + 10,
    y: y - 14,
    size: 16,
    font: fontBold,
    color: rgb(1, 1, 1),
  });
  page.drawText("AUTHORIZED RELEASE CERTIFICATE", {
    x: MARGIN + 10,
    y: y - 30,
    size: 9,
    font,
    color: rgb(0.7, 0.75, 0.85),
  });
  // EU flag placeholder text on right side
  page.drawText("EU", {
    x: PAGE_WIDTH - MARGIN - 30,
    y: y - 20,
    size: 14,
    font: fontBold,
    color: rgb(0.8, 0.85, 1),
  });
  y -= 48;

  // ── Block 1: Approving Competent Authority / Country ──
  y = drawSectionHeader(page, "BLOCK 1 — APPROVING COMPETENT AUTHORITY / COUNTRY", y, fontBold);
  y = drawField(page, "Competent Authority", content.block1 || "EASA", MARGIN + 5, y, font, fontBold, true);

  // ── Block 2: EASA Form 1 Header (static) ──
  drawLabel(page, "Block 2 — EASA FORM 1 AUTHORIZED RELEASE CERTIFICATE", MARGIN + 5, y, font);
  y -= 16;
  drawLine(page, y);

  // ── Block 3: Form Tracking Number ──
  y -= 8;
  y = drawField(page, "Block 3 — Form Tracking Number", content.block3 || "—", MARGIN + 5, y, font, fontBold, true);
  drawLine(page, y);

  // ── Block 4: Organization Name and Address ──
  y -= 8;
  y = drawSectionHeader(page, "BLOCK 4 — ORGANIZATION NAME AND ADDRESS", y, fontBold);
  y = drawWrappedText(page, content.block4 || "—", MARGIN + 5, y, CONTENT_WIDTH - 10, font, 9);
  y -= 8;
  drawLine(page, y);

  // ── Block 5: Work Order / Contract / Invoice ──
  y -= 8;
  y = drawField(page, "Block 5 — Work Order / Contract / Invoice", content.block5 || "—", MARGIN + 5, y, font, fontBold);
  drawLine(page, y);

  // ── Block 6: Item Identification (four sub-blocks in a row) ──
  y -= 4;
  y = drawSectionHeader(page, "BLOCK 6 — ITEM IDENTIFICATION", y, fontBold);
  const col6W = CONTENT_WIDTH / 4;
  const block6Fields = [
    { label: "6a. Description", value: content.block6a },
    { label: "6b. Part Number", value: content.block6b },
    { label: "6c. Serial Number", value: content.block6c },
    { label: "6d. Quantity", value: content.block6d },
  ];
  for (let i = 0; i < block6Fields.length; i++) {
    const x = MARGIN + 5 + col6W * i;
    drawLabel(page, block6Fields[i].label, x, y, font);
    page.drawText(block6Fields[i].value || "—", {
      x,
      y: y - 11,
      size: 9,
      font: fontBold,
      color: BLACK,
    });
  }
  y -= 28;
  drawLine(page, y);

  // ── Block 7: Remarks ──
  y -= 4;
  y = drawSectionHeader(page, "BLOCK 7 — REMARKS", y, fontBold);
  const remarks = content.block7 || "—";
  const remarkLines = remarks.split("\n").filter(Boolean);
  for (const line of remarkLines) {
    if (y < 160) break;
    y = drawWrappedText(page, line.trim(), MARGIN + 5, y, CONTENT_WIDTH - 10, font, 8);
    y -= 2;
  }
  y -= 4;
  drawLine(page, y);

  // ── Block 8-10: Release Type (Part 21 / Part 145) ──
  y -= 4;
  y = drawSectionHeader(page, "BLOCK 8-10 — RELEASE TO SERVICE", y, fontBold);

  // Block 8: Part 21 production release (if applicable)
  const hasBlock8 = content.block8 && content.block8 !== "N/A";
  drawLabel(page, "Block 8 — Part 21 (Production)", MARGIN + 5, y, font);
  page.drawText(hasBlock8 ? "[X]" : "[ ]", {
    x: MARGIN + 5 + 150,
    y: y - 1,
    size: 8,
    font: fontBold,
    color: BLACK,
  });
  if (hasBlock8) {
    page.drawText(content.block8, {
      x: MARGIN + 5 + 170,
      y: y,
      size: 8,
      font,
      color: BLACK,
    });
  }
  y -= 16;

  // Block 9: Part 145 maintenance release
  const hasBlock9 = content.block9 && content.block9 !== "N/A";
  drawLabel(page, "Block 9 — Part 145 (Maintenance)", MARGIN + 5, y, font);
  page.drawText(hasBlock9 ? "[X]" : "[ ]", {
    x: MARGIN + 5 + 150,
    y: y - 1,
    size: 8,
    font: fontBold,
    color: BLACK,
  });
  if (hasBlock9) {
    page.drawText(content.block9, {
      x: MARGIN + 5 + 170,
      y: y,
      size: 8,
      font,
      color: BLACK,
    });
  }
  y -= 16;

  // Block 10: Other regulation
  if (content.block10 && content.block10 !== "N/A") {
    drawLabel(page, "Block 10 — Other Regulation", MARGIN + 5, y, font);
    page.drawText(content.block10, {
      x: MARGIN + 5 + 150,
      y: y,
      size: 8,
      font,
      color: BLACK,
    });
    y -= 16;
  }
  drawLine(page, y);

  // ── Block 11: Approval / Authorization Number ──
  y -= 8;
  y = drawField(page, "Block 11 — Approval / Authorization Number", content.block11 || "—", MARGIN + 5, y, font, fontBold, true);

  // ── Block 12: Date ──
  y = drawField(page, "Block 12 — Date", content.block12 || "—", MARGIN + 5, y, font, fontBold);

  // ── Block 13: Authorized Signature ──
  y = drawField(page, "Block 13 — Authorized Signature", content.block13 || "[PENDING]", MARGIN + 5, y, font, fontBold, true);

  // ── Block 14: Certifying Statement ──
  y -= 4;
  drawLine(page, y);
  y -= 8;
  drawLabel(page, "Block 14 — Certifying Statement", MARGIN + 5, y, font);
  y -= 12;
  y = drawWrappedText(
    page,
    content.block14 || "Certifies that the items identified above were manufactured / maintained / overhauled in conformity with the approved data and are in a condition for safe operation.",
    MARGIN + 5,
    y,
    CONTENT_WIDTH - 10,
    font,
    8
  );

  // ── Hash fingerprint (tamper-evident) ──
  if (hash) {
    y -= 10;
    page.drawText(`SHA-256: ${hash}`, {
      x: MARGIN + 5,
      y,
      size: 6,
      font: courier,
      color: GRAY,
    });
  }

  // Footer
  drawFooter(page, font, hash);

  return pdf.save();
}

// ══════════════════════════════════════════════════════════════
// PDF RENDERER: FAA Form 8130-1
// ══════════════════════════════════════════════════════════════
// Application for Export Certificate of Airworthiness.
// Used when a repaired/overhauled part is being exported
// to a foreign civil aviation authority.

export async function render81301Pdf(
  content: Record<string, string>,
  hash?: string | null
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);

  let y = PAGE_HEIGHT - MARGIN;

  // ── Header ──
  page.drawRectangle({
    x: MARGIN,
    y: y - 38,
    width: CONTENT_WIDTH,
    height: 42,
    color: DARK_BLUE,
  });
  page.drawText("FAA FORM 8130-1", {
    x: MARGIN + 10,
    y: y - 14,
    size: 16,
    font: fontBold,
    color: rgb(1, 1, 1),
  });
  page.drawText("APPLICATION FOR EXPORT CERTIFICATE OF AIRWORTHINESS", {
    x: MARGIN + 10,
    y: y - 30,
    size: 8,
    font,
    color: rgb(0.7, 0.75, 0.85),
  });
  y -= 48;

  // ── Section 1: Applicant Information ──
  y = drawSectionHeader(page, "SECTION 1 — APPLICANT INFORMATION", y, fontBold);
  y = drawField(page, "Applicant Name", content.applicantName || "—", MARGIN + 5, y, font, fontBold, true);
  y = drawField(page, "Address", content.applicantAddress || "—", MARGIN + 5, y, font, fontBold);
  drawLine(page, y);

  // ── Section 2: Product Identification ──
  y -= 4;
  y = drawSectionHeader(page, "SECTION 2 — PRODUCT IDENTIFICATION", y, fontBold);
  const col2W = CONTENT_WIDTH / 3;
  const prodFields = [
    { label: "Type/Description", value: content.productType },
    { label: "Part Number", value: content.partNumber },
    { label: "Serial Number", value: content.serialNumber },
  ];
  for (let i = 0; i < prodFields.length; i++) {
    const x = MARGIN + 5 + col2W * i;
    drawLabel(page, prodFields[i].label, x, y, font);
    page.drawText(prodFields[i].value || "—", {
      x,
      y: y - 11,
      size: 9,
      font: fontBold,
      color: BLACK,
    });
  }
  y -= 28;

  y = drawField(page, "Manufacturer", content.manufacturer || "—", MARGIN + 5, y, font, fontBold);
  y = drawField(page, "Model Designation", content.modelDesignation || "—", MARGIN + 5, y, font, fontBold);
  drawLine(page, y);

  // ── Section 3: Export Destination ──
  y -= 4;
  y = drawSectionHeader(page, "SECTION 3 — EXPORT DESTINATION", y, fontBold);
  y = drawField(page, "Importing Country", content.importingCountry || "—", MARGIN + 5, y, font, fontBold, true);
  y = drawField(page, "Foreign Authority", content.foreignAuthority || "—", MARGIN + 5, y, font, fontBold);
  drawLine(page, y);

  // ── Section 4: Basis for Issuance ──
  y -= 4;
  y = drawSectionHeader(page, "SECTION 4 — BASIS FOR ISSUANCE", y, fontBold);
  y = drawWrappedText(page, content.basisForIssuance || "Product conforms to its type design and is in condition for safe operation.", MARGIN + 5, y, CONTENT_WIDTH - 10, font, 9);
  y -= 8;
  drawLine(page, y);

  // ── Section 5: Remarks ──
  y -= 4;
  y = drawSectionHeader(page, "SECTION 5 — REMARKS", y, fontBold);
  const remarks = content.remarks || "—";
  for (const line of remarks.split("\n").filter(Boolean)) {
    if (y < 160) break;
    y = drawWrappedText(page, line.trim(), MARGIN + 5, y, CONTENT_WIDTH - 10, font, 8);
    y -= 2;
  }
  y -= 4;
  drawLine(page, y);

  // ── Section 6: Certification ──
  y -= 4;
  y = drawSectionHeader(page, "SECTION 6 — CERTIFICATION", y, fontBold);
  const certCol = CONTENT_WIDTH / 3;
  const certFields = [
    { label: "FAA Inspector", value: content.inspectorName },
    { label: "Certificate Number", value: content.certificateNumber },
    { label: "Date", value: content.date },
  ];
  for (let i = 0; i < certFields.length; i++) {
    const x = MARGIN + 5 + certCol * i;
    drawLabel(page, certFields[i].label, x, y, font);
    page.drawText(certFields[i].value || "—", {
      x,
      y: y - 11,
      size: 9,
      font: fontBold,
      color: BLACK,
    });
  }
  y -= 28;
  y = drawField(page, "Signature", content.signature || "[PENDING]", MARGIN + 5, y, font, fontBold, true);

  // Footer
  drawFooter(page, font, hash);

  return pdf.save();
}

// ══════════════════════════════════════════════════════════════
// PDF RENDERER: FAA Form 8130-6
// ══════════════════════════════════════════════════════════════
// Application for U.S. Airworthiness Certificate.
// Filed when seeking initial or replacement airworthiness
// certification for an aircraft, engine, or propeller.

export async function render81306Pdf(
  content: Record<string, string>,
  hash?: string | null
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);

  let y = PAGE_HEIGHT - MARGIN;

  // ── Header ──
  page.drawRectangle({
    x: MARGIN,
    y: y - 38,
    width: CONTENT_WIDTH,
    height: 42,
    color: DARK_BLUE,
  });
  page.drawText("FAA FORM 8130-6", {
    x: MARGIN + 10,
    y: y - 14,
    size: 16,
    font: fontBold,
    color: rgb(1, 1, 1),
  });
  page.drawText("APPLICATION FOR U.S. AIRWORTHINESS CERTIFICATE", {
    x: MARGIN + 10,
    y: y - 30,
    size: 8,
    font,
    color: rgb(0.7, 0.75, 0.85),
  });
  y -= 48;

  // ── Section I: Aircraft Description ──
  y = drawSectionHeader(page, "SECTION I — AIRCRAFT DESCRIPTION", y, fontBold);
  const descCol = CONTENT_WIDTH / 4;
  const descFields = [
    { label: "Registration Mark", value: content.registrationMark },
    { label: "Aircraft Builder", value: content.aircraftBuilder },
    { label: "Model Designation", value: content.modelDesignation },
    { label: "Serial Number", value: content.serialNumber },
  ];
  for (let i = 0; i < descFields.length; i++) {
    const x = MARGIN + 5 + descCol * i;
    drawLabel(page, descFields[i].label, x, y, font);
    page.drawText(descFields[i].value || "—", {
      x,
      y: y - 11,
      size: 9,
      font: fontBold,
      color: BLACK,
    });
  }
  y -= 28;

  // Engine / Propeller
  const epCol = CONTENT_WIDTH / 2;
  const epFields = [
    { label: "Engine Builder & Model", value: content.engineModel },
    { label: "Propeller Builder & Model", value: content.propellerModel },
  ];
  for (let i = 0; i < epFields.length; i++) {
    const x = MARGIN + 5 + epCol * i;
    drawLabel(page, epFields[i].label, x, y, font);
    page.drawText(epFields[i].value || "N/A", {
      x,
      y: y - 11,
      size: 9,
      font,
      color: BLACK,
    });
  }
  y -= 28;
  drawLine(page, y);

  // ── Section II: Certificate Requested ──
  y -= 4;
  y = drawSectionHeader(page, "SECTION II — CERTIFICATE REQUESTED", y, fontBold);
  y = drawField(page, "Airworthiness Certificate Type", content.certificateType || "Standard", MARGIN + 5, y, font, fontBold, true);
  y = drawField(page, "Category", content.category || "—", MARGIN + 5, y, font, fontBold);
  if (content.operatingLimitations) {
    y = drawField(page, "Operating Limitations", content.operatingLimitations, MARGIN + 5, y, font, fontBold);
  }
  drawLine(page, y);

  // ── Section III: Certification Basis ──
  y -= 4;
  y = drawSectionHeader(page, "SECTION III — CERTIFICATION BASIS", y, fontBold);
  y = drawField(page, "Type Certificate Number", content.typeCertNumber || "—", MARGIN + 5, y, font, fontBold, true);
  y = drawField(page, "Production Basis", content.productionBasis || "—", MARGIN + 5, y, font, fontBold);
  drawLine(page, y);

  // ── Section IV: Remarks ──
  y -= 4;
  y = drawSectionHeader(page, "SECTION IV — REMARKS", y, fontBold);
  const remarks = content.remarks || "—";
  for (const line of remarks.split("\n").filter(Boolean)) {
    if (y < 160) break;
    y = drawWrappedText(page, line.trim(), MARGIN + 5, y, CONTENT_WIDTH - 10, font, 8);
    y -= 2;
  }
  y -= 4;
  drawLine(page, y);

  // ── Section V: Applicant Certification ──
  y -= 4;
  y = drawSectionHeader(page, "SECTION V — APPLICANT CERTIFICATION", y, fontBold);
  y = drawField(page, "Applicant Name", content.applicantName || "—", MARGIN + 5, y, font, fontBold, true);
  const sigCol = CONTENT_WIDTH / 2;
  drawLabel(page, "Signature", MARGIN + 5, y, font);
  page.drawText(content.applicantSignature || "[PENDING]", {
    x: MARGIN + 5,
    y: y - 11,
    size: 9,
    font: fontBold,
    color: BLACK,
  });
  drawLabel(page, "Date", MARGIN + 5 + sigCol, y, font);
  page.drawText(content.date || "—", {
    x: MARGIN + 5 + sigCol,
    y: y - 11,
    size: 9,
    font,
    color: BLACK,
  });
  y -= 28;

  // ── Section VI: FAA Representative ──
  y = drawSectionHeader(page, "SECTION VI — FAA REPRESENTATIVE", y, fontBold);
  drawLabel(page, "Inspector Signature", MARGIN + 5, y, font);
  page.drawText(content.inspectorSignature || "[PENDING]", {
    x: MARGIN + 5,
    y: y - 11,
    size: 9,
    font: fontBold,
    color: BLACK,
  });
  drawLabel(page, "Date", MARGIN + 5 + sigCol, y, font);
  page.drawText(content.inspectorDate || "—", {
    x: MARGIN + 5 + sigCol,
    y: y - 11,
    size: 9,
    font,
    color: BLACK,
  });

  // Footer
  drawFooter(page, font, hash);

  return pdf.save();
}

// ══════════════════════════════════════════════════════════════
// PDF RENDERER: Org-Form (Dimensional Inspection Record)
// ══════════════════════════════════════════════════════════════
export async function renderOrgFormPdf(
  content: Record<string, string>,
  hash?: string | null
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const GREEN = rgb(0.13, 0.55, 0.13);
  const RED = rgb(0.75, 0.1, 0.1);

  let page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - 40;

  // Add a new page if running out of space
  function ensureSpace(needed: number) {
    if (y - needed < 60) {
      drawFooter(page, font, hash);
      page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      y = PAGE_HEIGHT - 40;
    }
  }

  // ── Title header ──
  page.drawRectangle({
    x: MARGIN,
    y: y - 30,
    width: CONTENT_WIDTH,
    height: 35,
    color: LIGHT_GRAY,
  });
  const title = content._documentTitle || "DIMENSIONAL INSPECTION RECORD";
  page.drawText(title.toUpperCase(), {
    x: MARGIN + 10,
    y: y - 18,
    size: 13,
    font: fontBold,
    color: DARK_BLUE,
  });
  page.drawText("Generated by AeroVision", {
    x: MARGIN + 10,
    y: y - 28,
    size: 7,
    font,
    color: GRAY,
  });
  y -= 45;
  drawLine(page, y);

  // ── Header fields (Part Number, Serial Number, Work Order, Date) ──
  y -= 5;
  const headerLabels = ["Part Number", "Serial Number", "Work Order", "Date", "Inspector"];
  const headerEntries = headerLabels
    .map((label) => {
      const key = Object.keys(content).find(
        (k) => k.toLowerCase().replace(/[_\s-]/g, "") === label.toLowerCase().replace(/[_\s-]/g, "")
      );
      return { label, value: key ? content[key] : "" };
    })
    .filter((h) => h.value);

  if (headerEntries.length > 0) {
    const colWidth = CONTENT_WIDTH / Math.min(headerEntries.length, 3);
    for (let i = 0; i < headerEntries.length; i++) {
      const col = i % 3;
      if (i > 0 && col === 0) y -= 30;
      const hx = MARGIN + 5 + col * colWidth;
      drawLabel(page, headerEntries[i].label, hx, y, font);
      page.drawText(headerEntries[i].value || "—", {
        x: hx,
        y: y - 11,
        size: 10,
        font: fontBold,
        color: BLACK,
      });
    }
    y -= 30;
    drawLine(page, y);
  }

  // ── Group measurement fields by section ──
  const measurementKeys = Object.keys(content).filter(
    (k) =>
      !k.startsWith("_") &&
      !headerLabels.some(
        (h) => h.toLowerCase().replace(/[_\s-]/g, "") === k.toLowerCase().replace(/[_\s-]/g, "")
      )
  );

  // Group by section using _section_<key> metadata
  const sectionMap = new Map<string, { key: string; name: string; spec: string; actual: string }[]>();
  for (const key of measurementKeys) {
    const sectionKey = `_section_${key}`;
    const section = content[sectionKey] || "Measurements";
    const specKey = `_spec_${key}`;
    const spec = content[specKey] || "";

    if (!sectionMap.has(section)) sectionMap.set(section, []);
    sectionMap.get(section)!.push({
      key,
      name: key.replace(/_/g, " "),
      spec,
      actual: content[key] || "",
    });
  }

  // ── Table column widths ──
  const numCol = 25;
  const nameCol = 180;
  const specCol = 145;
  const actualCol = 90;
  const ROW_HEIGHT = 16;

  // Draw table header row
  function drawTableHeader() {
    ensureSpace(ROW_HEIGHT + 20);
    page.drawRectangle({
      x: MARGIN,
      y: y - ROW_HEIGHT + 2,
      width: CONTENT_WIDTH,
      height: ROW_HEIGHT,
      color: LIGHT_GRAY,
    });
    let cx = MARGIN + 4;
    page.drawText("#", { x: cx, y: y - 9, size: 7, font: fontBold, color: DARK_BLUE });
    cx += numCol;
    page.drawText("MEASUREMENT", { x: cx, y: y - 9, size: 7, font: fontBold, color: DARK_BLUE });
    cx += nameCol;
    page.drawText("SPECIFICATION", { x: cx, y: y - 9, size: 7, font: fontBold, color: DARK_BLUE });
    cx += specCol;
    page.drawText("ACTUAL", { x: cx, y: y - 9, size: 7, font: fontBold, color: DARK_BLUE });
    cx += actualCol;
    page.drawText("STATUS", { x: cx, y: y - 9, size: 7, font: fontBold, color: DARK_BLUE });
    y -= ROW_HEIGHT + 2;
  }

  let measurementNum = 0;
  let passCount = 0;
  let failCount = 0;
  let totalWithActual = 0;

  for (const [section, rows] of sectionMap) {
    ensureSpace(ROW_HEIGHT * 3);
    y = drawSectionHeader(page, section.toUpperCase(), y, fontBold);
    y -= 4;

    drawTableHeader();

    for (const row of rows) {
      measurementNum++;
      ensureSpace(ROW_HEIGHT + 4);

      // Zebra stripe on even rows
      if (measurementNum % 2 === 0) {
        page.drawRectangle({
          x: MARGIN,
          y: y - ROW_HEIGHT + 4,
          width: CONTENT_WIDTH,
          height: ROW_HEIGHT,
          color: rgb(0.97, 0.97, 0.97),
        });
      }

      let cx = MARGIN + 4;
      page.drawText(String(measurementNum), { x: cx, y: y - 8, size: 7.5, font, color: GRAY });
      cx += numCol;

      const displayName = row.name.length > 35 ? row.name.slice(0, 33) + "..." : row.name;
      page.drawText(displayName, { x: cx, y: y - 8, size: 7.5, font, color: BLACK });
      cx += nameCol;

      const specDisplay = row.spec.replace(/^spec:\s*/i, "").trim();
      const specTrunc = specDisplay.length > 28 ? specDisplay.slice(0, 26) + "..." : specDisplay;
      page.drawText(specTrunc || "—", { x: cx, y: y - 8, size: 7.5, font, color: GRAY });
      cx += specCol;

      page.drawText(row.actual || "—", { x: cx, y: y - 8, size: 8, font: fontBold, color: BLACK });
      cx += actualCol;

      // Compute pass/fail from spec range and actual value
      const specParsed = parseSpecRange(row.spec);
      const actualNum = parseActualValue(row.actual);
      let status = "—";
      let statusColor = GRAY;

      if (actualNum !== null && specParsed) {
        const result = checkPassFail(actualNum, specParsed);
        status = result;
        statusColor = result === "PASS" ? GREEN : RED;
        totalWithActual++;
        if (result === "PASS") passCount++;
        else failCount++;
      } else if (row.actual && row.actual !== "—") {
        status = "N/A";
        totalWithActual++;
      }

      page.drawText(status, { x: cx, y: y - 8, size: 8, font: fontBold, color: statusColor });

      y -= ROW_HEIGHT;
    }
    y -= 6;
  }

  // ── Summary ──
  ensureSpace(50);
  y -= 10;
  drawLine(page, y);
  y -= 18;
  page.drawText("SUMMARY", { x: MARGIN + 5, y, size: 9, font: fontBold, color: DARK_BLUE });
  y -= 14;
  page.drawText(`Total Measurements: ${measurementNum}`, {
    x: MARGIN + 5, y, size: 8, font, color: BLACK,
  });
  y -= 12;
  page.drawText(`Filled: ${totalWithActual} of ${measurementNum}`, {
    x: MARGIN + 5, y, size: 8, font, color: BLACK,
  });
  if (passCount > 0 || failCount > 0) {
    y -= 12;
    page.drawText(`Pass: ${passCount}  |  Fail: ${failCount}`, {
      x: MARGIN + 5, y, size: 8, font: fontBold, color: failCount > 0 ? RED : GREEN,
    });
  }

  drawFooter(page, font, hash);

  return pdf.save();
}
