// Shared PDF renderer functions for FAA compliance documents
// Used by the download route and unit tests
// Renders 8130-3, 337, and 8010-4 forms using pdf-lib

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

// ── Shared types for pdf-lib page drawing ──
type PDFPage = ReturnType<
  Awaited<ReturnType<typeof PDFDocument.create>>["addPage"]
>;
type PDFFont = Awaited<
  ReturnType<Awaited<ReturnType<typeof PDFDocument.create>>["embedFont"]>
>;

// ── Constants ──
const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN = 40;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const BLACK = rgb(0, 0, 0);
const GRAY = rgb(0.4, 0.4, 0.4);
const LIGHT_GRAY = rgb(0.85, 0.85, 0.85);
const DARK_BLUE = rgb(0.1, 0.15, 0.35);

// ── Shared helper: wrap text to fit within a max width ──
// Returns the Y position after drawing all lines.
function drawWrappedText(
  page: PDFPage,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  textFont: PDFFont,
  fontSize: number,
  color = BLACK
): number {
  const words = text.split(/\s+/);
  let line = "";
  let currentY = y;

  for (const word of words) {
    const testLine = line ? `${line} ${word}` : word;
    const testWidth = textFont.widthOfTextAtSize(testLine, fontSize);
    if (testWidth > maxWidth && line) {
      page.drawText(line, {
        x,
        y: currentY,
        size: fontSize,
        font: textFont,
        color,
      });
      currentY -= fontSize + 3;
      line = word;
    } else {
      line = testLine;
    }
  }
  if (line) {
    page.drawText(line, {
      x,
      y: currentY,
      size: fontSize,
      font: textFont,
      color,
    });
    currentY -= fontSize + 3;
  }
  return currentY;
}

// ── Shared helper: draw a horizontal rule ──
function drawLine(page: PDFPage, y: number) {
  page.drawLine({
    start: { x: MARGIN, y },
    end: { x: PAGE_WIDTH - MARGIN, y },
    thickness: 0.5,
    color: GRAY,
  });
}

// ── Shared helper: draw a small gray field label ──
function drawLabel(
  page: PDFPage,
  text: string,
  x: number,
  y: number,
  font: PDFFont
) {
  page.drawText(text, { x, y, size: 6.5, font, color: GRAY });
}

// ── Shared helper: draw a section header bar ──
function drawSectionHeader(
  page: PDFPage,
  text: string,
  y: number,
  fontBold: PDFFont
): number {
  page.drawRectangle({
    x: MARGIN,
    y: y - 14,
    width: CONTENT_WIDTH,
    height: 18,
    color: LIGHT_GRAY,
  });
  page.drawText(text, {
    x: MARGIN + 8,
    y: y - 10,
    size: 8,
    font: fontBold,
    color: DARK_BLUE,
  });
  return y - 22;
}

// ── Shared helper: draw a labeled field (label + value) ──
function drawField(
  page: PDFPage,
  label: string,
  value: string,
  x: number,
  y: number,
  font: PDFFont,
  fontBold: PDFFont,
  bold = false
): number {
  page.drawText(label, { x, y, size: 6.5, font, color: GRAY });
  page.drawText(value || "—", {
    x,
    y: y - 11,
    size: bold ? 10 : 9,
    font: bold ? fontBold : font,
    color: BLACK,
  });
  return y - 26;
}

// ── Shared helper: AeroVision footer ──
function drawFooter(page: PDFPage, font: PDFFont, hash?: string | null) {
  const y = 35;
  page.drawRectangle({
    x: MARGIN,
    y: y - 5,
    width: CONTENT_WIDTH,
    height: 18,
    color: LIGHT_GRAY,
  });
  page.drawText(
    "AeroVision Digital Verification  |  Tamper-evident  |  Generated by AeroVision AI v1.0",
    { x: MARGIN + 10, y: y, size: 6.5, font, color: GRAY }
  );
  if (hash) {
    page.drawText(`SHA-256: ${hash}`, {
      x: PAGE_WIDTH - MARGIN - 120,
      y: y,
      size: 6,
      font,
      color: GRAY,
    });
  }
}

// ══════════════════════════════════════════════════════════════
// PDF RENDERER: FAA Form 8130-3
// ══════════════════════════════════════════════════════════════
export async function render8130Pdf(
  content: Record<string, string>,
  hash?: string | null
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const fontMono = await pdf.embedFont(StandardFonts.Courier);

  let page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - 40;
  const midX = MARGIN + CONTENT_WIDTH / 2;

  // Form header
  page.drawRectangle({
    x: MARGIN,
    y: y - 30,
    width: CONTENT_WIDTH,
    height: 35,
    color: LIGHT_GRAY,
  });
  page.drawText("AUTHORIZED RELEASE CERTIFICATE", {
    x: MARGIN + 10,
    y: y - 18,
    size: 14,
    font: fontBold,
    color: DARK_BLUE,
  });
  page.drawText("FAA Form 8130-3", {
    x: MARGIN + 10,
    y: y - 28,
    size: 7,
    font,
    color: GRAY,
  });
  page.drawText("OMB No. 2120-0020", {
    x: PAGE_WIDTH - MARGIN - 100,
    y: y - 18,
    size: 7,
    font,
    color: GRAY,
  });
  y -= 45;
  drawLine(page, y);

  // Block 1 & 2
  y -= 5;
  drawLabel(
    page,
    "1. Approving Civil Aviation Authority / Country",
    MARGIN + 5,
    y,
    font
  );
  y -= 12;
  page.drawText(content.block1 || "FAA", {
    x: MARGIN + 5,
    y,
    size: 10,
    font: fontBold,
    color: BLACK,
  });
  drawLabel(page, "2. Authorized Release Document", midX + 10, y + 12, font);
  page.drawText(content.block2 || "Authorized Release Certificate", {
    x: midX + 10,
    y,
    size: 9,
    font,
    color: BLACK,
  });
  page.drawLine({
    start: { x: midX, y: y + 18 },
    end: { x: midX, y: y - 16 },
    thickness: 0.5,
    color: GRAY,
  });
  y -= 25;
  drawLine(page, y);

  // Block 3 & 4
  y -= 5;
  drawLabel(page, "3. Form Tracking Number", MARGIN + 5, y, font);
  y -= 12;
  page.drawText(content.block3 || "—", {
    x: MARGIN + 5,
    y,
    size: 10,
    font: fontMono,
    color: DARK_BLUE,
  });
  drawLabel(page, "4. Organization Name and Address", midX + 10, y + 12, font);
  const block4Lines = (content.block4 || "—").split("\n");
  let block4Y = y;
  for (const line of block4Lines) {
    page.drawText(line.trim(), {
      x: midX + 10,
      y: block4Y,
      size: 8,
      font,
      color: BLACK,
    });
    block4Y -= 11;
  }
  page.drawLine({
    start: { x: midX, y: y + 18 },
    end: { x: midX, y: Math.min(block4Y + 5, y - 10) },
    thickness: 0.5,
    color: GRAY,
  });
  y = Math.min(block4Y + 5, y - 15) - 10;
  drawLine(page, y);

  // Block 5
  y -= 5;
  drawLabel(
    page,
    "5. Work Order / Contract / Invoice Number",
    MARGIN + 5,
    y,
    font
  );
  y -= 12;
  page.drawText(content.block5 || "—", {
    x: MARGIN + 5,
    y,
    size: 9,
    font: fontMono,
    color: BLACK,
  });
  y -= 15;
  drawLine(page, y);

  // Block 6 — Item details
  y -= 5;
  const col6Width = CONTENT_WIDTH / 5;
  drawLabel(page, "6a. Item Description", MARGIN + 5, y, font);
  y -= 12;
  page.drawText(content.block6a || "—", {
    x: MARGIN + 5,
    y,
    size: 9,
    font: fontBold,
    color: BLACK,
  });
  const row6Y = y - 20;
  drawLabel(page, "6b. Part Number", MARGIN + 5, row6Y + 8, font);
  page.drawText(content.block6b || "—", {
    x: MARGIN + 5,
    y: row6Y - 4,
    size: 10,
    font: fontMono,
    color: BLACK,
  });
  drawLabel(
    page,
    "6c. Serial Number",
    MARGIN + col6Width * 2,
    row6Y + 8,
    font
  );
  page.drawText(content.block6c || "—", {
    x: MARGIN + col6Width * 2,
    y: row6Y - 4,
    size: 10,
    font: fontMono,
    color: BLACK,
  });
  drawLabel(page, "6d. Qty", MARGIN + col6Width * 4, row6Y + 8, font);
  page.drawText(content.block6d || "1", {
    x: MARGIN + col6Width * 4,
    y: row6Y - 4,
    size: 10,
    font: fontMono,
    color: BLACK,
  });
  y = row6Y - 20;

  // 6e — Status
  drawLabel(page, "6e. Status / Work", MARGIN + 5, y, font);
  y -= 12;
  const statuses = [
    "Overhauled",
    "Repaired",
    "Inspected",
    "Modified",
    "Tested",
    "New",
  ];
  let statusX = MARGIN + 5;
  for (const status of statuses) {
    const checked =
      (content.block6e || "").toLowerCase() === status.toLowerCase();
    page.drawRectangle({
      x: statusX,
      y: y - 2,
      width: 8,
      height: 8,
      borderColor: BLACK,
      borderWidth: 0.5,
      color: checked ? rgb(0.15, 0.15, 0.15) : rgb(1, 1, 1),
    });
    if (checked)
      page.drawText("X", {
        x: statusX + 1.5,
        y: y - 0.5,
        size: 7,
        font: fontBold,
        color: rgb(1, 1, 1),
      });
    page.drawText(status, {
      x: statusX + 11,
      y,
      size: 7.5,
      font,
      color: BLACK,
    });
    statusX += font.widthOfTextAtSize(status, 7.5) + 22;
  }
  y -= 18;
  drawLine(page, y);

  // Block 7 — Remarks (long content, handles page overflow)
  y -= 5;
  drawLabel(page, "7. Description — Status / Work", MARGIN + 5, y, font);
  y -= 14;
  const block7Lines = (content.block7 || "—").split("\n");
  for (const rawLine of block7Lines) {
    const trimmed = rawLine.trim();
    if (!trimmed) {
      y -= 6;
      continue;
    }
    const isHeading =
      trimmed === trimmed.toUpperCase() &&
      trimmed.length < 50 &&
      trimmed.length > 3;
    if (y < 80) {
      page.drawText(`Page ${pdf.getPageCount()}`, {
        x: PAGE_WIDTH - MARGIN - 40,
        y: 25,
        size: 7,
        font,
        color: GRAY,
      });
      page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      y = PAGE_HEIGHT - 50;
      drawLabel(
        page,
        "7. Description — Status / Work (continued)",
        MARGIN + 5,
        y,
        font
      );
      y -= 14;
    }
    y = drawWrappedText(
      page,
      trimmed,
      MARGIN + 10,
      y,
      CONTENT_WIDTH - 20,
      isHeading ? fontBold : font,
      isHeading ? 8.5 : 8
    );
    y -= 2;
  }
  y -= 5;
  drawLine(page, y);

  // Blocks 8-14 (if space, otherwise new page)
  if (y < 200) {
    page.drawText(`Page ${pdf.getPageCount()}`, {
      x: PAGE_WIDTH - MARGIN - 40,
      y: 25,
      size: 7,
      font,
      color: GRAY,
    });
    page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    y = PAGE_HEIGHT - 50;
  }

  // Blocks 8-10
  y -= 5;
  drawLabel(page, "8–10. Eligibility / Conformity", MARGIN + 5, y, font);
  y -= 12;
  page.drawText(
    "[X] Condition for safe operation    [X] FAR § 43.9, 14 CFR Part 145",
    { x: MARGIN + 10, y, size: 7.5, font, color: BLACK }
  );
  y -= 15;
  drawLine(page, y);

  // Blocks 11 & 12
  y -= 5;
  drawLabel(
    page,
    "11. Approval / Authorization Number",
    MARGIN + 5,
    y,
    font
  );
  drawLabel(page, "12. Date", midX + 10, y, font);
  y -= 12;
  page.drawText(content.block11 || "—", {
    x: MARGIN + 5,
    y,
    size: 9,
    font: fontMono,
    color: BLACK,
  });
  page.drawText(content.block12 || "—", {
    x: midX + 10,
    y,
    size: 9,
    font: fontMono,
    color: BLACK,
  });
  y -= 20;
  drawLine(page, y);

  // Block 13 — Signature
  y -= 5;
  drawLabel(page, "13. Authorized Signature", MARGIN + 5, y, font);
  y -= 15;
  page.drawRectangle({
    x: MARGIN + 10,
    y: y - 25,
    width: 180,
    height: 30,
    borderColor: GRAY,
    borderWidth: 0.5,
  });
  page.drawText(content.block13 || "[PENDING E-SIGNATURE]", {
    x: MARGIN + 20,
    y: y - 15,
    size: 8,
    font,
    color: GRAY,
  });
  page.drawText(`Date: ${content.block12 || "—"}`, {
    x: MARGIN + 210,
    y: y - 5,
    size: 8,
    font,
    color: BLACK,
  });
  page.drawText(`Auth: ${content.block11 || "—"}`, {
    x: MARGIN + 210,
    y: y - 18,
    size: 8,
    font,
    color: BLACK,
  });
  y -= 40;
  drawLine(page, y);

  // Block 14
  y -= 5;
  drawLabel(page, "14. Certifying Statement", MARGIN + 5, y, font);
  y -= 12;
  drawWrappedText(
    page,
    content.block14 || "—",
    MARGIN + 5,
    y,
    CONTENT_WIDTH - 10,
    font,
    7.5
  );

  // Footer
  drawFooter(page, font, hash);
  page.drawText(`Page ${pdf.getPageCount()}`, {
    x: PAGE_WIDTH - MARGIN - 40,
    y: 25,
    size: 7,
    font,
    color: GRAY,
  });

  return pdf.save();
}

// ══════════════════════════════════════════════════════════════
// PDF RENDERER: FAA Form 337 — Major Repair and Alteration
// ══════════════════════════════════════════════════════════════
export async function render337Pdf(
  content: Record<string, unknown>,
  hash?: string | null
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const fontMono = await pdf.embedFont(StandardFonts.Courier);

  const page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - 40;

  // Header
  page.drawRectangle({
    x: MARGIN,
    y: y - 30,
    width: CONTENT_WIDTH,
    height: 35,
    color: LIGHT_GRAY,
  });
  page.drawText("MAJOR REPAIR AND ALTERATION", {
    x: MARGIN + 10,
    y: y - 18,
    size: 14,
    font: fontBold,
    color: DARK_BLUE,
  });
  page.drawText("FAA Form 337 (10/06)", {
    x: MARGIN + 10,
    y: y - 28,
    size: 7,
    font,
    color: GRAY,
  });
  page.drawText("OMB No. 2120-0020", {
    x: PAGE_WIDTH - MARGIN - 100,
    y: y - 18,
    size: 7,
    font,
    color: GRAY,
  });
  y -= 50;
  drawLine(page, y);

  // Parse sub-objects
  const aircraft = (content.aircraft || {}) as Record<string, string>;
  const owner = (content.owner || {}) as Record<string, string>;
  const appliance = (content.appliance || {}) as Record<string, string>;
  const conformity = (content.conformity || {}) as Record<string, string>;
  const approval = (content.approval || {}) as Record<string, string>;

  // Section 1: Aircraft
  y = drawSectionHeader(page, "1. AIRCRAFT", y, fontBold);
  y -= 5;
  const colW = CONTENT_WIDTH / 4;
  const fields1 = [
    { label: "Nationality & Registration", value: aircraft.registration },
    { label: "Serial No.", value: aircraft.serialNumber },
    { label: "Make", value: aircraft.make },
    { label: "Model / Series", value: aircraft.model },
  ];
  for (let i = 0; i < fields1.length; i++) {
    const x = MARGIN + 5 + colW * i;
    drawLabel(page, fields1[i].label, x, y, font);
    page.drawText(fields1[i].value || "—", {
      x,
      y: y - 11,
      size: 10,
      font: i === 0 ? fontMono : font,
      color: i === 0 ? DARK_BLUE : BLACK,
    });
  }
  y -= 30;
  drawLine(page, y);

  // Section 2: Owner
  y = drawSectionHeader(page, "2. OWNER", y, fontBold);
  y -= 5;
  drawLabel(page, "Name", MARGIN + 5, y, font);
  page.drawText(owner.name || "—", {
    x: MARGIN + 5,
    y: y - 11,
    size: 9,
    font: fontBold,
    color: BLACK,
  });
  const midX = MARGIN + CONTENT_WIDTH / 2;
  drawLabel(page, "Address", midX, y, font);
  const ownerAddr = (owner.address || "—").split("\n");
  let addrY = y - 11;
  for (const line of ownerAddr) {
    page.drawText(line.trim(), {
      x: midX,
      y: addrY,
      size: 8,
      font,
      color: BLACK,
    });
    addrY -= 11;
  }
  y = Math.min(addrY, y - 30) - 5;
  drawLine(page, y);

  // Section 3: Type and Unit Identification
  y = drawSectionHeader(
    page,
    "3. TYPE AND UNIT IDENTIFICATION",
    y,
    fontBold
  );
  y -= 5;
  drawLabel(page, "Type", MARGIN + 5, y, font);
  page.drawText(
    `[X] ${(content.repairType as string) || "Repair"}`,
    { x: MARGIN + 5, y: y - 11, size: 8, font, color: BLACK }
  );
  drawLabel(page, "Unit", MARGIN + 100, y, font);
  page.drawText((content.unit as string) || "APPLIANCE", {
    x: MARGIN + 100,
    y: y - 11,
    size: 8,
    font: fontBold,
    color: BLACK,
  });
  y -= 30;

  // Appliance details
  const appFields = [
    { label: "Make", value: appliance.make },
    { label: "Model / Part No.", value: appliance.model, mono: true },
    { label: "Serial No.", value: appliance.serialNumber, mono: true },
    { label: "Type", value: appliance.type },
  ];
  for (let i = 0; i < appFields.length; i++) {
    const x = MARGIN + 5 + colW * i;
    drawLabel(page, appFields[i].label, x, y, font);
    page.drawText(appFields[i].value || "—", {
      x,
      y: y - 11,
      size: 9,
      font: appFields[i].mono ? fontMono : font,
      color: appFields[i].mono ? DARK_BLUE : BLACK,
    });
  }
  y -= 30;
  drawLine(page, y);

  // Section 4: Conformity Statement
  y = drawSectionHeader(page, "6. CONFORMITY STATEMENT", y, fontBold);
  y -= 5;
  y = drawField(
    page,
    "A. Agency",
    conformity.agency?.split("\n")[0] || "—",
    MARGIN + 5,
    y,
    font,
    fontBold
  );
  y = drawField(
    page,
    "B. Kind of Agency",
    `[X] ${conformity.agencyKind || "Certificated Repair Station"}`,
    MARGIN + 5,
    y,
    font,
    fontBold
  );
  y = drawField(
    page,
    "C. Certificate Number",
    conformity.certificateNumber || "—",
    MARGIN + 5,
    y,
    font,
    fontBold,
    true
  );

  // Certification text
  y -= 5;
  y = drawWrappedText(
    page,
    "D. I certify that the repair made to the unit(s) identified above has been made in accordance with the requirements of Part 43 of the U.S. Federal Aviation Regulations.",
    MARGIN + 5,
    y,
    CONTENT_WIDTH - 10,
    font,
    7.5
  );
  y -= 5;
  page.drawText(conformity.signedBy || "—", {
    x: MARGIN + 10,
    y,
    size: 12,
    font: fontBold,
    color: DARK_BLUE,
  });
  page.drawText(`Date: ${conformity.date || "—"}`, {
    x: MARGIN + 200,
    y,
    size: 8,
    font,
    color: BLACK,
  });
  y -= 20;
  drawLine(page, y);

  // Section 5: Approval for Return to Service
  y = drawSectionHeader(
    page,
    "7. APPROVAL FOR RETURN TO SERVICE",
    y,
    fontBold
  );
  y -= 5;
  page.drawText(
    `[X] ${approval.status || "Approved"}    ${approval.type || "Repair Station"}    Certificate: ${approval.certificate || "—"}`,
    { x: MARGIN + 5, y, size: 8, font, color: BLACK }
  );
  y -= 15;
  page.drawText(approval.signedBy || "—", {
    x: MARGIN + 10,
    y,
    size: 12,
    font: fontBold,
    color: DARK_BLUE,
  });
  page.drawText(`Date: ${approval.date || "—"}`, {
    x: MARGIN + 200,
    y,
    size: 8,
    font,
    color: BLACK,
  });
  y -= 20;
  drawLine(page, y);

  // Section 6: Description of Work
  y = drawSectionHeader(
    page,
    "8. DESCRIPTION OF WORK ACCOMPLISHED",
    y,
    fontBold
  );
  y -= 8;
  const workLines = ((content.workDescription as string) || "—").split("\n");
  for (const rawLine of workLines) {
    const trimmed = rawLine.trim();
    if (!trimmed) {
      y -= 6;
      continue;
    }
    if (y < 70) break; // don't overflow past footer
    y = drawWrappedText(
      page,
      trimmed,
      MARGIN + 5,
      y,
      CONTENT_WIDTH - 10,
      font,
      8
    );
    y -= 2;
  }

  // Footer
  drawFooter(page, font, hash);

  return pdf.save();
}

// ══════════════════════════════════════════════════════════════
// PDF RENDERER: FAA Form 8010-4 — Malfunction or Defect Report
// ══════════════════════════════════════════════════════════════
export async function render8010Pdf(
  content: Record<string, unknown>,
  hash?: string | null
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const fontMono = await pdf.embedFont(StandardFonts.Courier);

  const page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - 40;

  // Header
  page.drawRectangle({
    x: MARGIN,
    y: y - 30,
    width: CONTENT_WIDTH,
    height: 35,
    color: LIGHT_GRAY,
  });
  page.drawText("MALFUNCTION OR DEFECT REPORT", {
    x: MARGIN + 10,
    y: y - 18,
    size: 14,
    font: fontBold,
    color: DARK_BLUE,
  });
  page.drawText("FAA Form 8010-4 (10-92)", {
    x: MARGIN + 10,
    y: y - 28,
    size: 7,
    font,
    color: GRAY,
  });
  page.drawText("OMB No. 2120-0663", {
    x: PAGE_WIDTH - MARGIN - 100,
    y: y - 18,
    size: 7,
    font,
    color: GRAY,
  });
  y -= 50;
  drawLine(page, y);

  // Parse sub-objects
  const aircraft = (content.aircraft || {}) as Record<string, string>;
  const defectPart = (content.defectPart || {}) as Record<string, string>;
  const componentAssembly = (content.componentAssembly || {}) as Record<
    string,
    string
  >;
  const metrics = (content.metrics || {}) as Record<string, string>;
  const submittedBy = (content.submittedBy || {}) as Record<string, string>;
  const colW = CONTENT_WIDTH / 4;

  // Section 1: Aircraft Identification
  y = drawSectionHeader(page, "1. AIRCRAFT IDENTIFICATION", y, fontBold);
  y -= 5;
  const acFields = [
    { label: "Registration No.", value: aircraft.registration, mono: true },
    { label: "Manufacturer", value: aircraft.manufacturer },
    { label: "Model / Series", value: aircraft.model },
    { label: "Serial Number", value: aircraft.serialNumber },
  ];
  for (let i = 0; i < acFields.length; i++) {
    const x = MARGIN + 5 + colW * i;
    drawLabel(page, acFields[i].label, x, y, font);
    page.drawText(acFields[i].value || "—", {
      x,
      y: y - 11,
      size: 10,
      font: acFields[i].mono ? fontMono : font,
      color: acFields[i].mono ? DARK_BLUE : BLACK,
    });
  }
  y -= 30;
  drawLine(page, y);

  // Section 2: Specific Part Causing Trouble
  y = drawSectionHeader(
    page,
    "5. SPECIFIC PART CAUSING TROUBLE",
    y,
    fontBold
  );
  y -= 5;
  const partFields = [
    { label: "Part Name", value: defectPart.name, bold: true },
    {
      label: "MFG Model / Part No.",
      value: defectPart.partNumber,
      mono: true,
    },
    { label: "Serial No.", value: defectPart.serialNumber },
    { label: "Part/Defect Location", value: defectPart.location },
  ];
  for (let i = 0; i < partFields.length; i++) {
    const x = MARGIN + 5 + colW * i;
    drawLabel(page, partFields[i].label, x, y, font);
    const pFont = partFields[i].mono
      ? fontMono
      : partFields[i].bold
        ? fontBold
        : font;
    const pColor = partFields[i].mono
      ? DARK_BLUE
      : partFields[i].bold
        ? rgb(0.6, 0.3, 0)
        : BLACK;
    page.drawText(partFields[i].value || "—", {
      x,
      y: y - 11,
      size: 9,
      font: pFont,
      color: pColor,
    });
  }
  y -= 30;
  drawLine(page, y);

  // Section 3: Component / Appliance
  y = drawSectionHeader(
    page,
    "6. APPLIANCE / COMPONENT (Assembly That Includes Part)",
    y,
    fontBold
  );
  y -= 5;
  const compFields = [
    { label: "Name", value: componentAssembly.name },
    { label: "Manufacturer", value: componentAssembly.manufacturer },
    {
      label: "Model / Part No.",
      value: componentAssembly.partNumber,
      mono: true,
    },
    {
      label: "Serial Number",
      value: componentAssembly.serialNumber,
      mono: true,
    },
  ];
  for (let i = 0; i < compFields.length; i++) {
    const x = MARGIN + 5 + colW * i;
    drawLabel(page, compFields[i].label, x, y, font);
    page.drawText(compFields[i].value || "—", {
      x,
      y: y - 11,
      size: 9,
      font: compFields[i].mono ? fontMono : font,
      color: compFields[i].mono ? DARK_BLUE : BLACK,
    });
  }
  y -= 30;
  drawLine(page, y);

  // Section 4: Metrics
  y = drawSectionHeader(page, "PART METRICS", y, fontBold);
  y -= 5;
  const metricFields = [
    { label: "Part Total Time", value: metrics.partTotalTime },
    { label: "Part TSO", value: metrics.partTSO },
    { label: "Part Condition", value: metrics.partCondition },
    {
      label: "Date Submitted",
      value: (content.dateSubmitted as string) || "—",
    },
  ];
  for (let i = 0; i < metricFields.length; i++) {
    const x = MARGIN + 5 + colW * i;
    drawLabel(page, metricFields[i].label, x, y, font);
    const isCondition = metricFields[i].label === "Part Condition";
    page.drawText(metricFields[i].value || "—", {
      x,
      y: y - 11,
      size: 9,
      font: isCondition ? fontBold : font,
      color: isCondition ? rgb(0.6, 0.3, 0) : BLACK,
    });
  }
  y -= 30;
  drawLine(page, y);

  // Section 5: Comments (long narrative)
  y = drawSectionHeader(page, "8. COMMENTS", y, fontBold);
  y -= 8;
  const commentLines = ((content.comments as string) || "—").split("\n");
  for (const rawLine of commentLines) {
    const trimmed = rawLine.trim();
    if (!trimmed) {
      y -= 6;
      continue;
    }
    const isHeading =
      trimmed === trimmed.toUpperCase() &&
      trimmed.length < 50 &&
      trimmed.length > 3;
    if (y < 100) break;
    y = drawWrappedText(
      page,
      trimmed,
      MARGIN + 5,
      y,
      CONTENT_WIDTH - 10,
      isHeading ? fontBold : font,
      8
    );
    y -= 2;
  }
  y -= 5;
  drawLine(page, y);

  // Section 6: Submitted By
  y -= 10;
  const subFields = [
    { label: "Submitted By", value: submittedBy.type },
    { label: "Operator Designation", value: submittedBy.designation },
    { label: "Telephone", value: submittedBy.telephone },
  ];
  const subColW = CONTENT_WIDTH / 3;
  for (let i = 0; i < subFields.length; i++) {
    const x = MARGIN + 5 + subColW * i;
    drawLabel(page, subFields[i].label, x, y, font);
    page.drawText(subFields[i].value || "—", {
      x,
      y: y - 11,
      size: 9,
      font,
      color: BLACK,
    });
  }

  // Footer
  drawFooter(page, font, hash);

  return pdf.save();
}
